"""Mirage Score: a transparent 0-100 verdict built from named components.

Components (weights always visible in the component table):
  - dsr            Deflated Sharpe Ratio p-value          (0.20)
  - pbo            Probability of Backtest Overfitting     (0.25)
  - rc             Reality Check p-value                   (0.20)
  - degradation    IS-vs-OOS Sharpe retention              (0.15)
  - cost_fragility breakeven transaction cost              (0.10)
  - length         backtest length vs MinBTL               (0.10)

Labels: score >= 65 -> "Survives"; 40-65 -> "Unclear"; < 40 -> "Mirage"
(likely overfit).  Hard gate: when a benchmark is supplied, a Reality Check
p > 0.5 caps the label at "Unclear" - you cannot certify skill the Reality
Check says is not there.  Narrative sentences are generated by rules - no LLM.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

WEIGHTS = {
    "dsr": 0.20,
    "pbo": 0.25,
    "rc": 0.20,
    "degradation": 0.15,
    "cost_fragility": 0.10,
    "length": 0.10,
}


@dataclass
class Component:
    key: str
    label: str
    weight: float
    score: float  # 0-100
    detail: str


@dataclass
class Verdict:
    score: float
    label: str  # "Mirage" | "Unclear" | "Survives"
    components: list[Component] = field(default_factory=list)
    narrative: list[str] = field(default_factory=list)


def _clip(x: float, lo: float = 0.0, hi: float = 100.0) -> float:
    return float(np.clip(x, lo, hi))


def build_verdict(
    dsr_p: float,
    pbo: float,
    is_sharpe: float,
    oos_sharpe_median: float,
    breakeven_bps: float,
    assumed_cost_bps: float,
    n_days: int,
    min_btl: float,
    n_trials: int,
    rc_p: float | None = None,
    breakeven_capped: bool = False,
    period_unit: str = "days",
) -> Verdict:
    comps: list[Component] = []
    narrative: list[str] = []

    s_dsr = _clip(100 * dsr_p)
    comps.append(Component("dsr", "Deflated Sharpe p-value", WEIGHTS["dsr"], s_dsr,
                           f"DSR p-value = {dsr_p:.2f} across {n_trials} trials"))
    if dsr_p < 0.10:
        narrative.append(
            f"After deflating for {n_trials} recorded trials, the probability the "
            f"best result reflects real skill is only {dsr_p:.0%}."
        )
    elif dsr_p > 0.50:
        narrative.append(
            f"The Deflated Sharpe Ratio still assigns {dsr_p:.0%} probability to "
            f"genuine skill after accounting for {n_trials} trials."
        )

    s_pbo = _clip(100 * (1 - pbo))
    comps.append(Component("pbo", "PBO (CSCV)", WEIGHTS["pbo"], s_pbo,
                           f"PBO = {pbo:.2f}: probability the IS winner is below median OOS"))
    if pbo > 0.5:
        narrative.append(
            f"In {pbo:.0%} of combinatorial splits the in-sample winner fell below "
            f"the median out of sample - a classic overfitting signature."
        )
    elif pbo < 0.25:
        narrative.append(
            f"The in-sample winner stayed above the OOS median in {1 - pbo:.0%} of splits."
        )

    if rc_p is not None:
        s_rc = _clip(100 * (1 - rc_p))
        comps.append(Component("rc", "Reality Check", WEIGHTS["rc"], s_rc,
                               f"White RC p = {rc_p:.2f}: does the best trial beat "
                               f"the benchmark beyond luck?"))
        if rc_p > 0.5:
            narrative.append(
                f"The best trial does not beat the benchmark beyond luck "
                f"(Reality Check p = {rc_p:.2f})."
            )
        elif rc_p < 0.10:
            narrative.append(
                f"The Reality Check rejects pure luck: the best trial's edge over "
                f"the benchmark is significant (p = {rc_p:.2f})."
            )

    ratio = 0.0 if is_sharpe <= 0 else oos_sharpe_median / is_sharpe
    s_deg = _clip(100 * min(max(ratio, 0.0), 1.2))
    comps.append(Component("degradation", "IS-vs-OOS retention", WEIGHTS["degradation"],
                           s_deg,
                           f"median OOS Sharpe {oos_sharpe_median:.2f} vs "
                           f"median IS {is_sharpe:.2f} across CSCV splits"))
    if is_sharpe > 0 and ratio < 0.5:
        narrative.append(
            f"The selected configuration kept only {ratio:.0%} of its in-sample "
            f"Sharpe out of sample."
        )

    denom = max(3.0 * assumed_cost_bps, 15.0)
    s_cost = _clip(100 * min(breakeven_bps / denom, 1.0))
    cost_detail = (f"> {breakeven_bps:.0f} bps (never crosses zero on the grid)"
                   if breakeven_capped else
                   f"Sharpe hits zero at {breakeven_bps:.0f} bps "
                   f"(assumed {assumed_cost_bps:.0f} bps)")
    comps.append(Component("cost_fragility", "Cost fragility", WEIGHTS["cost_fragility"],
                           s_cost, cost_detail))
    if breakeven_bps < 2 * assumed_cost_bps:
        narrative.append(
            f"Edge is fragile to frictions: net Sharpe reaches zero near "
            f"{breakeven_bps:.0f} bps of transaction cost."
        )

    if np.isfinite(min_btl) and min_btl > 0:
        s_len = _clip(100 * min(n_days / min_btl, 1.0))
        len_detail = f"{n_days} {period_unit} vs minimum {min_btl:.0f} required"
    else:
        s_len = 0.0
        len_detail = "minimum length unbounded (Sharpe <= benchmark)"
    comps.append(Component("length", "Backtest length", WEIGHTS["length"], s_len, len_detail))
    if np.isfinite(min_btl) and n_days < min_btl:
        narrative.append(
            f"The backtest covers {n_days} {period_unit} but needs ~{min_btl:.0f} for the "
            f"claimed Sharpe to be significant at 95%."
        )

    w_sum = sum(c.weight for c in comps)
    score = float(sum(c.weight * c.score for c in comps) / w_sum)
    if rc_p is None:
        narrative.append(
            "No benchmark supplied - the Reality Check component is omitted and "
            "the remaining weights are renormalized."
        )
    if score >= 65:
        label = "Survives"
    elif score >= 40:
        label = "Unclear"
    else:
        label = "Mirage"
    if label == "Survives" and rc_p is not None and rc_p > 0.5:
        label = "Unclear"
        narrative.append(
            "Score cleared the Survives bar, but the Reality Check does not "
            "confirm the edge beats the benchmark beyond luck - label capped "
            "at Unclear."
        )
    if not narrative:
        narrative.append("Diagnostics are mixed; inspect the component table before acting.")
    return Verdict(score=round(score, 1), label=label, components=comps, narrative=narrative)
